// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Queue struct {
	ID             int32     `json:"id"`
	DueDate        time.Time `json:"due_date"`
	ProcessedCount int32     `json:"processed_count"`
}
