// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	BatchGet(ctx context.Context, dollar_1 int32) ([]*BatchGetRow, error)
	SetProcessed(ctx context.Context, dollar_1 []int32) *SetProcessedBatchResults
}

var _ Querier = (*Queries)(nil)
